### ISSUE TITLE
서버 아이피 변경시 오류

### ISSUE THREAD

**Issue by oleho** [miumida/naver_weather#1]
스마트폰 termux 환경에서 HA구성중입니다.

Wifi 환경에서 LTE 환경 변경 후엔 오류가 나타납니다.

0|hass  | 2020-05-20 16:10:31 ERROR (SyncWorker_0) [custom_components.naver_weather.weather] Failed to update NWeather API status Error: 'NoneType' object has no attribute 'text'                    
0|hass  | 2020-05-20 16:10:32 ERROR (SyncWorker_3) [custom_components.naver_weather.sensor] Failed to update NWeather API status Error: 'NoneType' object has no attribute 'text'                     
0|hass  | 2020-05-20 16:10:32 ERROR (MainThread) [homeassistant.components.weather] Error while setting up naver_weather platform for weather                                                         
0|hass  | Traceback (most recent call last):                      
0|hass  |   File "/data/data/com.termux/files/home/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform                            
0|hass  |     await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)                                                     
0|hass  |   File "/data/data/com.termux/files/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for                            
0|hass  |     return fut.result()                                 
0|hass  |   File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run                      
0|hass  |     result = self.fn(*self.args, self.kwargs)         
0|hass  |   File "/data/data/com.termux/files/home/.homeassistant/custom_components/naver_weather/weather.py", line 83, in setup_platform                                                             
0|hass  |     api.update()                                        
0|hass  |   File "/data/data/com.termux/files/home/.homeassistant/custom_components/naver_weather/weather.py", line 117, in update  
0|hass  |     LocationInfo = soup.find('span', {'class':'btn_select'}).text                                                         
0|hass  | AttributeError: 'NoneType' object has no attribute 'text'                                                                 
0|hass  | 2020-05-20 16:10:32 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up naver_weather platform for sensor                                                           
0|hass  | Traceback (most recent call last):                      
0|hass  |   File "/data/data/com.termux/files/home/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform                            
0|hass  |     await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)                                                     
0|hass  |   File "/data/data/com.termux/files/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for                            
0|hass  |     return fut.result()                                 
0|hass  |   File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
0|hass  |     result = self.fn(*self.args, self.kwargs)         
0|hass  |   File "/data/data/com.termux/files/home/.homeassistant/custom_components/naver_weather/sensor.py", line 73, in setup_platform                                                              
0|hass  |     api.update()                                        
0|hass  |   File "/data/data/com.termux/files/home/.homeassistant/custom_components/naver_weather/sensor.py", line 105, in update   
0|hass  |     LocationInfo = soup.find('span', {'class':'btn_select'}).text                                                         
0|hass  | AttributeError: 'NoneType' object has no attribute 'text'                                                                 
0|hass  | -----------------------------------------

**Comment by miumida** [comment]
LTE로 변경되면서 request는 pc버전 주소로 보내지만, 내부적으로 모바일페이지로 접속이 되는거 같아보이네요.

**Comment by oleho** [comment]
헤더에 user-agent 추가 해주실순 있을실까요?

**Comment by miumida** [comment]
1.2.0 버전에서 헤더정보 넣었습니다.
확인해보시면 될거같네요.
