### ISSUE TITLE
[이슈] 버그 수정 사항 및 제안사항 반영 요청

### ISSUE THREAD

**Issue by minseokhappylee** [miumida/naver_weather#10]
혹시 아래 사항 기여해도 무방한지 문의드립니다.

수정은 완료되어있습니다.

버그
   : 오늘비시작시간 및 오늘내일비시작시간 항목 조회 시 "소나기"에 대해서는 반영되지 않음.

기능 추가
   : 자외선지수 항목 추가

**Comment by miumida** [comment]
PR해주시면 보고 merge 시키겠습니다^^

**Comment by miumida** [comment]
다른 수정 건과 함께 요청하셨던 내용 반영하였습니다.
좋은 의견 주신 것 감사합니다!

**Comment by minseokhappylee** [comment]
네 적용 감사합니다! 그런데 자외선 지수를 부득이하게 사용하고 있어서 혹시 Fork로 제 리포지토리를 별도로 유지해도 무방한지 문의드립니다.
