### ISSUE TITLE
weather.naver_weather_1 구성요소에 오늘 날씨 요약을 추가해 주실 수 있을까요?

### ISSUE THREAD

**Issue by Murianwind** [miumida/naver_weather#13]
안녕하세요.

만들어 주신 네이버 날씨는 엄청 감사한 마음으로 잘 사용하고 있습니다.

소소한 수정 사항 하나 요청드려봅니다.

제가 현재 Clock Weather Card(https://github.com/pkissling/clock-weather-card) 라는 러브레이스 카드를 사용하고 있습니다.

이 카드는 날씨 컴포넌트에서 오늘 날씨 요약이 존재하면 현재 온도를 표시해주는 기능이 있습니다.

![화면 캡처 2022-11-18 081835](https://user-images.githubusercontent.com/6447460/202580519-f64c9bc0-6d89-42ed-80b5-70ae2c88eba9.png)

그런데, 네이버 날씨는 오늘 정보는 표시되지 않아서 이 정보가 표시되지 않는데요..

혹시 weather.naver_weather_1 구성요소에 오늘 날씨 정보를 추가해 주실 수 있을까요?

제가 미력하나마 수정해볼까 하고 코드를 들여다보았는데.. 음.. 제가 어떻게 할 수 있는 그런게 아니네요..

코딩 지식이 워낙에 미천해서..

혹시 고려해보시고 어렵지 않다면 추가해 주시면 고맙겠습니다.

**Comment by miumida** [comment]
주간예보에 오늘날씨 포함 옵션을 추가하였습니다.
업데이트 하고 다시 설정하시면 될거 같네요.

**Comment by Murianwind** [comment]
감사합니다. 새해 복 많이 받으세요.
