### ISSUE TITLE
 Failed to update NWeather API NowTemp

### ISSUE THREAD

**Issue by auspic7** [miumida/naver_weather#6]
Hello.
just restarted ha, and encountered this error.
I think it's kinda involved about failed http response

> This error originated from a custom integration.
> 
> Logger: custom_components.naver_weather.api_nweather
> Source: custom_components/naver_weather/api_nweather.py:145
> Integration: Naver Weather (documentation)
> First occurred: 3:56:02 PM (1 occurrences)
> Last logged: 3:56:02 PM
> 
> Failed to update NWeather API NowTemp Error : 'NoneType' object has no attribute 'text'

**Comment by miumida** [comment]
지역에 입력된 값으로 네이보에서 검색했을때 결과가 다르게 나오는거 같습니다. 지역으로 입력한 값이랑 확인해 보세요.
